/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classroom.attendance.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Dictionary;
import java.util.Hashtable;
import javax.swing.JOptionPane;

/**
 *
 * @author uwagb
 */
public class CourseRegistrationView extends javax.swing.JFrame {
private final Dictionary<String, Integer> courseNameDict;
private int userID;
private int departmentID;
    /**
     * Creates new form CourseRegistrationView
     */
    public CourseRegistrationView(int userID, int departmentID) {
        initComponents();
        this.courseNameDict = new Hashtable<String, Integer>();
        this.userID = userID;
        this.departmentID = departmentID;
        populateStudentInfo();
        populateComboBox();
        populateDataList();
    }

    
    
    public void populateStudentInfo(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/CAS", "root", "example");
            PreparedStatement ps = con.prepareStatement(""
                    + "select FirstName, LastName from User where UserID=?");
            ps.setInt(1, this.userID);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                student_name_label.setText(rs.getString("FirstName")
                        +" "+ rs.getString("LastName"));
            }
            
            PreparedStatement ps1 = con.prepareStatement(""
                    + "select Name from Department where DepartmentID in("
                    + "select DepartmentID from Student where UserID=?"
                    + ")");
            ps1.setInt(1,this.userID);
            ResultSet rs1 = ps1.executeQuery();
            
            while(rs1.next()){
                department_label.setText(rs1.getString("Name"));
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }
    
    public void populateComboBox(){
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/CAS", "root", "example");
            PreparedStatement ps = con.prepareStatement("select * from Course where DepartmentID=?");
            ps.setInt(1, this.departmentID);
            ResultSet rs = ps.executeQuery();
            
            
            while(rs.next()){
               //System.out.println(rs.getString("Name"));
               
               combo_box.addItem(rs.getString("Name"));
               this.courseNameDict.put(rs.getString("Name"), rs.getInt("CourseID"));
                
            }
            
        }catch(Exception e){
            System.out.print(e);
        }
    }
    
    
    public void populateDataList(){
        String[] items = new String[5];
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/CAS", "root", "example");
            PreparedStatement ps = con.prepareStatement(""
                    + "select Name, CourseID from Course where CourseID in("
                    + "select CourseID from StudentCourse where StudentID in ("
                    + "select StudentID from Student where UserID=?"
                    + ")"
                    + ")");
            ps.setInt(1, this.userID);
            ResultSet rs = ps.executeQuery();
            
            int position = 0;
            while(rs.next()){
                items[position] = rs.getString("Name");
                //this.courseNameDict.put(rs.getString("Name"), rs.getInt("CourseID"));
                position++;
                
            }
            
            data_list.setListData(items);
            
            //populateComboBox();
            
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_name_label = new javax.swing.JLabel();
        department_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_list = new javax.swing.JList<>();
        combo_box = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        student_name_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        student_name_label.setText("Student's Name");

        department_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        department_label.setText("Department");

        data_list.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        data_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data_list);

        combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_boxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Courses Offered ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(student_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(256, 256, 256)
                .addComponent(department_label, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_name_label)
                    .addComponent(department_label))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_listMouseClicked
        // TODO add your handling code here:
        String item_clicked = data_list.getSelectedValue();
        if(item_clicked != null){
            int CourseID = this.courseNameDict.get(item_clicked);

            int value = JOptionPane.showConfirmDialog(rootPane,
                "Are you sure you want to remove course", "Course Removal", 0, 2);

            if (value == 0){
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/CAS", "root", "example");
                    PreparedStatement ps = con.prepareStatement("delete from StudentCourse where CourseID=?");
                    ps.setInt(1, CourseID);
                    ps.execute();
                    con.close();

                    populateDataList();
                    // HODAllocateCourseToLecturerView.populateDataTable(this.departmentID);
                }catch(Exception e){
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_data_listMouseClicked

    
    public boolean checkForCourseMultiplicity(int userID, int courseID){
        boolean isMultiple = false;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CAS", "root", "example");
            PreparedStatement ps = con.prepareStatement("select * from StudentCourse where StudentID in("
                    + "select StudentID from Student where UserID=?"
                    + ") and CourseID=?");
            ps.setInt(1, userID);
            ps.setInt(2,courseID);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                isMultiple = true;
                break;
            }
        }catch(Exception e){
            System.out.println(e);
        }
        System.out.println(isMultiple);
        return isMultiple;
    } 
    
    
    private void combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_boxActionPerformed
        // TODO add your handling code here:
        String selectedCourse = combo_box.getSelectedItem().toString();

        if (selectedCourse != null){
            int CourseID = this.courseNameDict.get(selectedCourse);
            int value = JOptionPane.showConfirmDialog(rootPane,
                "Are you sure you want to add " + selectedCourse , "Course Addition", 0, 2);
            if (value == 0){

                if(!checkForCourseMultiplicity(this.userID, CourseID)){
                    try{
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CAS", "root", "example");
                        PreparedStatement ps1 = con.prepareStatement("select StudentID from Student where UserID=?");
                        ps1.setInt(1, this.userID);
                        ResultSet rs1 = ps1.executeQuery();
                        
                        while(rs1.next()){
                            PreparedStatement ps = con.prepareStatement("insert into StudentCourse("
                            + "StudentID,CourseID"
                            + ")"
                            + "values (?,?)");
                            ps.setInt(1, rs1.getInt("StudentID"));
                            ps.setInt(2, CourseID);
                            ps.executeUpdate();
                            break;
                        }
                        
                        con.close();

                        populateDataList();
                        //HODAllocateCourseToLecturerView.populateDataTable(this.departmentID);
                    }catch(Exception e){
                        System.out.println(e);
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Course already assigned to Student", "Error", 0);
                }
            }
        }
    }//GEN-LAST:event_combo_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CourseRegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_box;
    private javax.swing.JList<String> data_list;
    private javax.swing.JLabel department_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel student_name_label;
    // End of variables declaration//GEN-END:variables
}
