/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classroom.attendance.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author uwagb
 */
public class FacultyLogIn extends javax.swing.JFrame {

    /**
     * Creates new form FacultyLogIn
     */
    public FacultyLogIn() {
        initComponents();
    }

    public class Faculty{
        String first_name;
        String last_name;
        String middle_name;
        String gender;
        String date_of_birth;
        String email;
        String phone_number;
        protected byte image[];
        protected byte Fingerprint[];
        String password;
        String role;
        int department;
        
        Faculty(String firstName, String lastName, String middleName, String gender,
                String dateOfBirth, String email, String phoneNumber, byte[] image,
                byte[] fingerPrint, String password, String role, int department){
            
            this.first_name = firstName;
            this.last_name = lastName;
            this.middle_name = middleName;
            this.gender = gender;
            this.date_of_birth = dateOfBirth;
            this.email = email;
            this.phone_number = phoneNumber;
            this.image = image;
            this.Fingerprint = fingerPrint;
            this.password = password;
            this.role = role;
            this.department = department;
        }
        
        
        public void changePassword(){
            
        }
        
        public void changeImage(){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        login_email_label = new javax.swing.JLabel();
        login_email_field = new javax.swing.JTextField();
        login_password_label = new javax.swing.JLabel();
        login_show_password_radio_button = new javax.swing.JRadioButton();
        login_button = new javax.swing.JButton();
        login_password_field = new javax.swing.JPasswordField();
        signup_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black)));

        login_email_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login_email_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_email_label.setText("Email");

        login_email_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        login_password_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login_password_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_password_label.setText("Password");

        login_show_password_radio_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login_show_password_radio_button.setText("Show Password");
        login_show_password_radio_button.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black)));
        login_show_password_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_show_password_radio_buttonActionPerformed(evt);
            }
        });

        login_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login_button.setText("Login");
        login_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        login_password_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        login_password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_password_fieldActionPerformed(evt);
            }
        });

        signup_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signup_button.setText("Signup");
        signup_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(login_show_password_radio_button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(login_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(login_email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(login_password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(login_email_field)
                                    .addComponent(login_password_field))))))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login_password_label)
                    .addComponent(login_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(login_show_password_radio_button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login_button)
                .addGap(18, 18, 18)
                .addComponent(signup_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FACULTY LOGIN PAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_show_password_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_show_password_radio_buttonActionPerformed
        // TODO add your handling code here:
        if (login_show_password_radio_button.isSelected()){
            login_password_field.setEchoChar((char) 0);
            
        }else{
            login_password_field.setEchoChar('*');
            //password_field_2.setEchoChar('*');
        }
    }//GEN-LAST:event_login_show_password_radio_buttonActionPerformed
    
    public String getGender(String text){
        String gender = null;
        if (text.equals("m")){
            gender = "Male";
        }
        if (text.equals("f")){
            gender = "Female";
        }
        return gender;
    }
    
    
    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        boolean facultyIsLoggedIn = false;
        String email = login_email_field.getText();
        String password = login_password_field.getText();
        String hashed_password = FacultySignUp.the_Hasher(password);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CAS", "root", "example");
            PreparedStatement ps = con.prepareStatement("select * from User");
            //ps.setString(1, email);
            
            ResultSet rs = ps.executeQuery();
            
            
            while (rs.next()){
                String retrieved_password = rs.getString("Password");
                String retrieved_email = rs.getString("Email");
                //  
                if (hashed_password.equals(retrieved_password) && email.equals(retrieved_email)){
                    facultyIsLoggedIn = true;
                    // Check if User is a Lecturer
                    PreparedStatement ps1 = con.prepareStatement(""
                            + "select LecturerID from Lecturer where FacultyID in("
                            + "select Faculty.FacultyID from Faculty where Faculty.UserID=?"
                            + ")"
                            + "");
                    ps1.setInt(1, rs.getInt("UserID"));
                    ResultSet rs1 = ps1.executeQuery();
                    boolean facultyIsLecturer = false;
                    
                    while(rs1.next()){
                        facultyIsLecturer = true;
                    }
                    // End
                    
                    // Check if User is a HOD
                    PreparedStatement ps2 = con.prepareStatement(""
                            + "select HODID from HOD where FacultyID in("
                            + "select Faculty.FacultyID from Faculty where Faculty.UserID=?"
                            + ")"
                            + "");
                    ps2.setInt(1, rs.getInt("UserID"));
                    ResultSet rs2 = ps2.executeQuery();
                    boolean facultyIsHOD = false;
                    
                    while(rs2.next()){
                        facultyIsHOD = true;
                    }
                    // End
                    
                    // Check if User is a Dean
                    PreparedStatement ps3 = con.prepareStatement(""
                            + "select DeanID from Dean where FacultyID in("
                            + "select Faculty.FacultyID from Faculty where Faculty.UserID=?"
                            + ")"
                            + "");
                    ps3.setInt(1, rs.getInt("UserID"));
                    ResultSet rs3 = ps3.executeQuery();
                    boolean facultyIsDean = false;
                    
                    while(rs3.next()){
                        facultyIsDean = true;
                    }
                    // End
                    
                    // Check if User is a Program Coordinator
                    PreparedStatement ps4 = con.prepareStatement(""
                            + "select ProgramCoordinatorID from ProgramCoordinator where FacultyID in("
                            + "select Faculty.FacultyID from Faculty where Faculty.UserID=?"
                            + ")"
                            + "");
                    ps4.setInt(1, rs.getInt("UserID"));
                    ResultSet rs4 = ps4.executeQuery();
                    boolean facultyIsProgramCoordinator = false;
                    
                    while(rs4.next()){
                        facultyIsProgramCoordinator = true;
                    }
                    // End
                    
                    // Get Faculty's Department
                    PreparedStatement ps5 = con.prepareStatement(""
                            + "select DepartmentID from Faculty where Faculty.UserID=?");
                    ps5.setInt(1,rs.getInt("UserID"));
                    ResultSet rs5 = ps5.executeQuery();
                    int departmentID = 0;
                    
                    while(rs5.next()){
                        departmentID = rs5.getInt("DepartmentID");
                    }
                    
                    String facultyRole = "";
                    if (facultyIsProgramCoordinator){
                        facultyRole = "Program Coordinator";
                    }
                    else if (facultyIsDean){
                        facultyRole = "Dean";
                    }
                    else if (facultyIsHOD){
                        facultyRole = "HOD";
                    }
                    else if (facultyIsLecturer){
                        facultyRole = "Lecturer";
                    }
                    
                    JOptionPane.showMessageDialog(rootPane, "User logged in", "Success",JOptionPane.INFORMATION_MESSAGE);
                    Faculty loggedInFaculty = new Faculty(rs.getString("FirstName"), rs.getString("LastName"),
                            rs.getString("MiddleName"), getGender(rs.getString("Gender")), rs.getString("DateOfBirth"),
                           rs.getString("Email"), rs.getString("PhoneNumber"),rs.getBytes("Image"),
                            rs.getBytes("FingerPrint"), rs.getString("Password"),
                            facultyRole, departmentID
                    );
                    
                    FacultyHomeView homeView = new FacultyHomeView(loggedInFaculty);
                    homeView.setVisible(true);
                    this.dispose();
                    con.close();
                    
                    login_email_field.setText(null);
                    login_password_field.setText(null);
                    break;
                }else{
                    
                }
            }
            if(!facultyIsLoggedIn){
                JOptionPane.showMessageDialog(rootPane, "Invalid Email or Password", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch (Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void login_password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_password_fieldActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        FacultySignUp newSignUp = new FacultySignUp();
        newSignUp.show();
        newSignUp.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_signup_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_button;
    private javax.swing.JTextField login_email_field;
    private javax.swing.JLabel login_email_label;
    private javax.swing.JPasswordField login_password_field;
    private javax.swing.JLabel login_password_label;
    private javax.swing.JRadioButton login_show_password_radio_button;
    private javax.swing.JButton signup_button;
    // End of variables declaration//GEN-END:variables
}
