/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classroom.attendance.system;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author uwagb
 */
public class StudentRegistrationView extends javax.swing.JFrame {
public String filename = null;
static byte photo[] = null;
public static ByteArrayInputStream FingerPrintData;
public static Integer FingerPrintSize;
private Insert newInsert;
private final Dictionary<String, Integer> departmentNameDict;
public static boolean status = false;

    /**
     * Creates new form StudentRegistrationView
     */
    public StudentRegistrationView() {
        initComponents();
        status = true;
        this.departmentNameDict = new Hashtable<String, Integer>();
        populateComboBox();
        StartFingerPrint();
    }

    public void StartFingerPrint(){
        newInsert = new Insert();
        newInsert.start();
    }
    
    public void addPlaceHolder(JTextField jtextField){
        
        Font font = jtextField.getFont();
        font.deriveFont(Font.ITALIC);
        jtextField.setFont(font);
        jtextField.setBackground(Color.RED);
    }
    
    public void removePlaceHolder(JTextField jtextField){
        Font font = jtextField.getFont();
        font.deriveFont(Font.PLAIN);
        jtextField.setFont(font);
        jtextField.setBackground(Color.RED);
        
    }
    
    
    public static String the_Hasher(String text){
        String hashed_text;
        try{
            MessageDigest msgDigest = MessageDigest.getInstance("SHA-256");
            msgDigest.update((text).getBytes("UTF8"));
            // String pass = new String(msgDigest.digest());
            
            hashed_text = new String(msgDigest.digest());
        }catch (UnsupportedEncodingException | NoSuchAlgorithmException e){
            hashed_text = text;
        }
    return hashed_text;
        
    }

    public void populateComboBox(){
        department_combo_box.removeAllItems();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CAS", "root", "example");
            PreparedStatement ps = con.prepareStatement("select * from Department");
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                System.out.println(rs.getString("Name"));
                department_combo_box.addItem(rs.getString("Name"));
                this.departmentNameDict.put(rs.getString("Name"), rs.getInt("DepartmentID"));
            }
            con.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        first_name_label = new javax.swing.JLabel();
        first_name_field = new javax.swing.JTextField();
        last_name_label = new javax.swing.JLabel();
        last_name_field = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        signup_email_field = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        phone_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        male_radio_button = new javax.swing.JRadioButton();
        female_radio_button = new javax.swing.JRadioButton();
        date_of_birth_label = new javax.swing.JLabel();
        date_of_birth_chooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        password_field_1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        password_field_2 = new javax.swing.JPasswordField();
        show_password_radio_button = new javax.swing.JRadioButton();
        signup_button = new javax.swing.JButton();
        middle_name_label = new javax.swing.JLabel();
        middle_name_field = new javax.swing.JTextField();
        faculty_id_label = new javax.swing.JLabel();
        matric_no_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        department_combo_box = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        first_year_radio_button = new javax.swing.JRadioButton();
        second_year_radio_button = new javax.swing.JRadioButton();
        third_year_radio_button = new javax.swing.JRadioButton();
        fourth_year_radio_button = new javax.swing.JRadioButton();
        fifth_year_radio_button = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        web_cam_button = new javax.swing.JButton();
        show_label = new javax.swing.JLabel();
        show_field = new javax.swing.JTextField();
        browse_button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        finger_print_show_label = new javax.swing.JLabel();
        dialog_box_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setText("STUDENT REGISTRATION PAGE");

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null), null));

        first_name_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        first_name_label.setText("First Name");

        first_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_name_fieldActionPerformed(evt);
            }
        });

        last_name_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        last_name_label.setText("Last Name");

        last_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_name_fieldActionPerformed(evt);
            }
        });

        email_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email_label.setText("Email");

        signup_email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_email_fieldActionPerformed(evt);
            }
        });

        phone_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phone_label.setText("Phone");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Sex");

        male_radio_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        male_radio_button.setText("Male");
        male_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_radio_buttonActionPerformed(evt);
            }
        });

        female_radio_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        female_radio_button.setText("Female");
        female_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radio_buttonActionPerformed(evt);
            }
        });

        date_of_birth_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        date_of_birth_label.setText("Date of Birth");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Confirm Password");

        show_password_radio_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        show_password_radio_button.setText("Show password");
        show_password_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_password_radio_buttonActionPerformed(evt);
            }
        });

        signup_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signup_button.setText("Signup");
        signup_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        middle_name_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        middle_name_label.setText("Middle Name");

        faculty_id_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        faculty_id_label.setText("Matric No.");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Have an account?");

        login_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Department");

        department_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        department_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department_combo_boxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Level");

        first_year_radio_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        first_year_radio_button.setText("100L");
        first_year_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_year_radio_buttonActionPerformed(evt);
            }
        });

        second_year_radio_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        second_year_radio_button.setText("200L");
        second_year_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_year_radio_buttonActionPerformed(evt);
            }
        });

        third_year_radio_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        third_year_radio_button.setText("300L");
        third_year_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                third_year_radio_buttonActionPerformed(evt);
            }
        });

        fourth_year_radio_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fourth_year_radio_button.setText("400L");
        fourth_year_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourth_year_radio_buttonActionPerformed(evt);
            }
        });

        fifth_year_radio_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fifth_year_radio_button.setText("500L");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(middle_name_label)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(first_name_label)
                            .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(faculty_id_label))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(signup_email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phone_label))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(male_radio_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(first_name_field)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(183, 183, 183)
                                        .addComponent(female_radio_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(middle_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(last_name_label)
                                    .addComponent(date_of_birth_label)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(matric_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password_field_1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(show_password_radio_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone_field)
                            .addComponent(last_name_field)
                            .addComponent(password_field_2)
                            .addComponent(date_of_birth_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(department_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(first_year_radio_button, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(second_year_radio_button)
                                .addGap(18, 18, 18)
                                .addComponent(third_year_radio_button)
                                .addGap(18, 18, 18)
                                .addComponent(fourth_year_radio_button)
                                .addGap(18, 18, 18)
                                .addComponent(fifth_year_radio_button)))))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(login_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(371, 371, 371))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(first_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(last_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(last_name_label))
                    .addComponent(first_name_label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middle_name_label)
                    .addComponent(middle_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_label)
                            .addComponent(signup_email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone_label)
                            .addComponent(phone_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(male_radio_button)
                                .addComponent(female_radio_button))
                            .addComponent(date_of_birth_label)
                            .addComponent(date_of_birth_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(password_field_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(password_field_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(show_password_radio_button))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(department_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faculty_id_label)
                    .addComponent(matric_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(first_year_radio_button)
                    .addComponent(second_year_radio_button)
                    .addComponent(third_year_radio_button)
                    .addComponent(fourth_year_radio_button)
                    .addComponent(fifth_year_radio_button))
                .addGap(33, 33, 33)
                .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(login_button))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null), null));

        web_cam_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        web_cam_button.setText("Web Camera");
        web_cam_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                web_cam_buttonActionPerformed(evt);
            }
        });

        show_label.setBackground(new java.awt.Color(255, 255, 255));
        show_label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        show_label.setOpaque(true);

        show_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_fieldActionPerformed(evt);
            }
        });

        browse_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        browse_button.setText("Browse");
        browse_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(show_field)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(show_label, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(browse_button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(web_cam_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(show_label, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show_field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browse_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(web_cam_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null)));

        finger_print_show_label.setBackground(new java.awt.Color(255, 255, 255));
        finger_print_show_label.setOpaque(true);

        dialog_box_label.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        dialog_box_label.setForeground(new java.awt.Color(0, 255, 0));
        dialog_box_label.setText("Dialog Box");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finger_print_show_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialog_box_label, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finger_print_show_label, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dialog_box_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void first_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_name_fieldActionPerformed

    private void last_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_name_fieldActionPerformed

    private void signup_email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_email_fieldActionPerformed

    private void male_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_radio_buttonActionPerformed
        // TODO add your handling code here:
        if (male_radio_button.isSelected()){
            female_radio_button.setSelected(false);
        }
    }//GEN-LAST:event_male_radio_buttonActionPerformed

    private void female_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radio_buttonActionPerformed
        // TODO add your handling code here:
        if (female_radio_button.isSelected()){
            male_radio_button.setSelected(false);
        }
    }//GEN-LAST:event_female_radio_buttonActionPerformed

    private void show_password_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_password_radio_buttonActionPerformed
        // TODO add your handling code here:
        if (show_password_radio_button.isSelected()){
            password_field_1.setEchoChar((char) 0);
            password_field_2.setEchoChar((char) 0);
        }else{
            password_field_1.setEchoChar('*');
            password_field_2.setEchoChar('*');
        }
    }//GEN-LAST:event_show_password_radio_buttonActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        try{
            String first_name = first_name_field.getText();
            String last_name = last_name_field.getText();
            String middle_name = middle_name_field.getText();
            String email = signup_email_field.getText();
            String phone_number = phone_field.getText();
            String matric_no = matric_no_field.getText();
            int departmentID = departmentNameDict.get(
                    department_combo_box.getSelectedItem().toString());
            String gender = null;
            String level = null;

            if (first_year_radio_button.isSelected()){
                level = "100L";
            }
            if (second_year_radio_button.isSelected()){
                level = "200L";
            }
            if (third_year_radio_button.isSelected()){
                level = "300L";
            }
            if (fourth_year_radio_button.isSelected()){
                level = "400L";
            }
            if (fifth_year_radio_button.isSelected()){
                level = "500L";
            }

            if (male_radio_button.isSelected()){
                gender = "m";

            }
            if (female_radio_button.isSelected()){
                gender = "f";
            }

            SimpleDateFormat dat = new SimpleDateFormat("yyyy-MM-dd");
            String dob = dat.format(date_of_birth_chooser.getDate());

            if (dob == null){
                JOptionPane.showMessageDialog(null,"Enter date", "Error", JOptionPane.ERROR_MESSAGE);
            }

            if (FingerPrintData == null || FingerPrintSize == null){
                JOptionPane.showMessageDialog(null,"Please provide Finger Print", "Error", JOptionPane.ERROR_MESSAGE);
            }

            boolean email_check = true, phone_check = true;
            String regex = "^[a-zA-Z0-9_!#$%&'*+/=?{|}~^.-]+@[a-zA-Z0-9.-]+$";

            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(email);

            if (matcher.matches()){

            }else{
                email_check = false;
                addPlaceHolder(signup_email_field);
            }

            if (!(Pattern.matches("^[0-9]{11}+$", phone_field.getText()))){
                phone_check = false;
                addPlaceHolder(phone_field);

            }else{

            }

            if ((email_check == false) || (phone_check == false)){
                JOptionPane.showMessageDialog(null, "Enter the required Information", "Error", JOptionPane.ERROR_MESSAGE);

            }else{

                if (password_field_1.getText().equals(password_field_2.getText())){
                    // int age = date_of_birth_chooser.getDate().getYear();

                    // MessageDigest msgDigest = MessageDigest.getInstance("SHA-256");
                    // msgDigest.update((password_field_1.getText()).getBytes("UTF8"));
                    // String pass = new String(msgDigest.digest());

                    String pass = the_Hasher(password_field_1.getText());

                    Class.forName("com.mysql.cj.jdbc.Driver");

                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CAS", "root", "example");
                    PreparedStatement ps = con.prepareStatement(""
                        + "Insert into User(FirstName, LastName, MiddleName, Gender, DateOfBirth, PhoneNumber, Image, Email, Password, FingerPrint) "
                        + "values(?,?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, first_name);
                    ps.setString(2, last_name);
                    ps.setString(3, middle_name);
                    ps.setString(4, gender);
                    ps.setString(5, dob);
                    ps.setString(6, phone_number);
                    ps.setBytes(7, photo);
                    ps.setString(8, email);
                    ps.setString(9, pass);
                    ps.setBinaryStream(10, FingerPrintData, FingerPrintSize);

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "User created");
                    
                    // Insert into Student Table
                    
                    
                    // Inserting into Faculty Table
                    ps = con.prepareStatement("select UserID from User where Email=?");
                    ps.setString(1, email);
                    ResultSet rs = ps.executeQuery();
                    //int UserID = 0;

                    while(rs.next()){
                        //UserID = rs.getInt("UserID");
                        ps = con.prepareStatement("insert into Student("
                                + "UserID,MatricNo,DepartmentID,Level"
                                + ") values(?,?,?,?)");
                        ps.setInt(1, rs.getInt("UserID"));
                        ps.setString(2, matric_no);
                        ps.setInt(3, departmentID);
                        ps.setString(4, level);
                        
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "User added as Student");
                        break;
                    }
                    
                    con.close();

                    first_name_field.setText(null);
                    last_name_field.setText(null);
                    signup_email_field.setText(null);
                    phone_field.setText(null);
                    male_radio_button.setSelected(false);
                    female_radio_button.setSelected(false);
                    first_year_radio_button.setSelected(false);
                    second_year_radio_button.setSelected(false);
                    third_year_radio_button.setSelected(false);
                    fourth_year_radio_button.setSelected(false);
                    fifth_year_radio_button.setSelected(false);
                    matric_no_field.setText(null);
                    date_of_birth_chooser.setDate(null);
                    password_field_1.setText(null);
                    password_field_2.setText(null);
                    show_label.setIcon(null);
                    show_field.setText(null);
                    finger_print_show_label.setIcon(null);
                    

                    //FacultyLogIn newLogin = new FacultyLogIn();
                    //newLogin.show();
                    //newLogin.setVisible(true);
                    //this.newInsert.stop();
                    //this.newInsert.dispose();
                    //this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Password Mismatch", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }

        }catch (HeadlessException | ClassNotFoundException | SQLException e){
            // System.out.println(e);
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signup_buttonActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        //FacultyLogIn newLogin = new FacultyLogIn();
        //newLogin.show();
        //newLogin.setVisible(true);
        this.newInsert.stop();
        this.newInsert.dispose();
        this.dispose();
    }//GEN-LAST:event_login_buttonActionPerformed

    private void web_cam_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_web_cam_buttonActionPerformed
        // TODO add your handling code here:
        // Capture photo = new Capture
        Capture newCapture = new Capture();
        newCapture.show();
        newCapture.setVisible(true);
    }//GEN-LAST:event_web_cam_buttonActionPerformed

    private void show_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_fieldActionPerformed

    private void browse_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_buttonActionPerformed
        // TODO add your handling code here:
        try {
            jFileChooser1.showOpenDialog(null);

            File file = jFileChooser1.getSelectedFile();
            filename = file.getAbsolutePath();
            String path = file.getAbsolutePath();
            show_field.setText(path);
            Image image = Toolkit.getDefaultToolkit().createImage(path);
            image = image.getScaledInstance(show_label.getWidth(),
                show_label.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(image);
            show_label.setIcon(icon);
            File image_ = new File(filename);
            FileInputStream files = new FileInputStream(image_);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte[] Byte = new byte[1024];

            for (int i; (i = files.read(Byte)) != -1;){
                baos.write(Byte, 0, i);
            }
            photo = baos.toByteArray();

        }catch (HeadlessException | IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_browse_buttonActionPerformed

    private void third_year_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_third_year_radio_buttonActionPerformed
        // TODO add your handling code here:
        if (third_year_radio_button.isSelected()){
            first_year_radio_button.setSelected(false);
            second_year_radio_button.setSelected(false);
            fourth_year_radio_button.setSelected(false);
            fifth_year_radio_button.setSelected(false);
        }
    }//GEN-LAST:event_third_year_radio_buttonActionPerformed

    private void first_year_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_year_radio_buttonActionPerformed
        // TODO add your handling code here:
        if (first_year_radio_button.isSelected()){
            second_year_radio_button.setSelected(false);
            third_year_radio_button.setSelected(false);
            fourth_year_radio_button.setSelected(false);
            fifth_year_radio_button.setSelected(false);
        }
        
    }//GEN-LAST:event_first_year_radio_buttonActionPerformed

    private void second_year_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_year_radio_buttonActionPerformed
        // TODO add your handling code here:
        if (second_year_radio_button.isSelected()){
            first_year_radio_button.setSelected(false);
            third_year_radio_button.setSelected(false);
            fourth_year_radio_button.setSelected(false);
            fifth_year_radio_button.setSelected(false);
        }
    }//GEN-LAST:event_second_year_radio_buttonActionPerformed

    private void fourth_year_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourth_year_radio_buttonActionPerformed
        // TODO add your handling code here:
        if (fourth_year_radio_button.isSelected()){
            first_year_radio_button.setSelected(false);
            second_year_radio_button.setSelected(false);
            third_year_radio_button.setSelected(false);
            fifth_year_radio_button.setSelected(false);
        }
    }//GEN-LAST:event_fourth_year_radio_buttonActionPerformed

    private void department_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department_combo_boxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_department_combo_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse_button;
    private com.toedter.calendar.JDateChooser date_of_birth_chooser;
    private javax.swing.JLabel date_of_birth_label;
    private javax.swing.JComboBox<String> department_combo_box;
    public static javax.swing.JLabel dialog_box_label;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel faculty_id_label;
    private javax.swing.JRadioButton female_radio_button;
    private javax.swing.JRadioButton fifth_year_radio_button;
    public static javax.swing.JLabel finger_print_show_label;
    private javax.swing.JTextField first_name_field;
    private javax.swing.JLabel first_name_label;
    private javax.swing.JRadioButton first_year_radio_button;
    private javax.swing.JRadioButton fourth_year_radio_button;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField last_name_field;
    private javax.swing.JLabel last_name_label;
    private javax.swing.JButton login_button;
    private javax.swing.JRadioButton male_radio_button;
    private javax.swing.JTextField matric_no_field;
    private javax.swing.JTextField middle_name_field;
    private javax.swing.JLabel middle_name_label;
    private javax.swing.JPasswordField password_field_1;
    private javax.swing.JPasswordField password_field_2;
    private javax.swing.JTextField phone_field;
    private javax.swing.JLabel phone_label;
    private javax.swing.JRadioButton second_year_radio_button;
    public static javax.swing.JTextField show_field;
    public static javax.swing.JLabel show_label;
    private javax.swing.JRadioButton show_password_radio_button;
    private javax.swing.JButton signup_button;
    private javax.swing.JTextField signup_email_field;
    private javax.swing.JRadioButton third_year_radio_button;
    private javax.swing.JButton web_cam_button;
    // End of variables declaration//GEN-END:variables
}
